[package]
name = "rustask"
version = "0.1.0"
authors = ["Zachary Allnutt <zrwall@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
