CREATE TABLE "Task" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Title"	TEXT NOT NULL,
	"Text"	TEXT NOT NULL,
	"CreatedBy"	INTEGER NOT NULL,
	"AssignedTo"	INTEGER NOT NULL,
	"WorkbookID"	INTEGER NOT NULL,
	FOREIGN KEY("CreatedBy") REFERENCES "User"("ID"),
	FOREIGN KEY("AssignedTo") REFERENCES "User"("ID"),
	FOREIGN KEY("WorkbookID") REFERENCES "Workbook"("ID")
)