CREATE TABLE "Permissions" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"WorkbookID"	INTEGER NOT NULL,
	"UserID"	INTEGER NOT NULL,
	"IsAdmin"	INTEGER NOT NULL CHECK(IsAdmin in (0, 1)),
	FOREIGN KEY("WorkbookID") REFERENCES "Workbook"("ID"),
	FOREIGN KEY("UserID") REFERENCES "User"("ID")
)